### PR TITLE
Refactor client to accept RequestQueryParameters

### PR DESCRIPTION
**Pull request by technodelight**
- [x] Change `getActivities` to accept `RequestQueryParameters` as argument
- [x] Make `RequestQueryParameters` immutable
- [x] Make tests pass

### CODE REVIEW

**Comment by technodelight** [comment]
Hello! As we discussed a couple of days ago, I made some changes to the client to accept a `RequestQueryParameters` object. I also made it immutable (so it's more like a value object now) and removed unnecessary properties (`api_key` and `format` would be explicitly passed from the `HttpClient` instead). I also made a couple of changes regarding the property validators and the exceptions thrown. Also, I noticed the `document` as a type of restrict kind has been missing, so added that as well. My bad.
I could have been done a bit more on the refactoring front, but didn't had the time, apologise :)
Hope you'll like it, although I have to admit this is a backward incompatible change.

**Comment by technodelight** [comment]
Also I see the Travis build fails. Is it worth to keep the testing phase against PHP 5.3, as it's already end of life?

**Comment by technodelight** [comment]
I updated the documentation to reflect the changes, and removed the obsolete PHP version from travis config.

**Comment by borivojevic** [comment]
Awesome work! As this is breaking change I'll have to bump version number to 2.0 before releasing the library.
- Thanks

**Comment by technodelight** [comment]
No worries, thanks for merging in!

**Pull request merged**
