### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by tamvodopad**
1. Add php7 to travis config.
2. Fix spaces.

### CODE REVIEW

**Comment by tamvodopad** [comment]
1. Add methots to DailyReport for Very Distracting Data

**Comment by borivojevic** [comment]
Great! I think we should just document these two new public methods in the Readme somehow.

**Comment by tamvodopad** [comment]
@borivojevic done!

**Comment by borivojevic** [comment]
Awesome, thank you.

**Pull request merged**
